name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # -------------------------------
    # 1. LOGIN TO AZURE
    # -------------------------------
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # -------------------------------
    # 2. DEPLOY AZURE FUNCTIONS BY ZIP
    # -------------------------------
    - name: Create Function ZIP
      run: |
        cd functions
        zip -r ../functions.zip .
        cd ..

    - name: Deploy Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --name bank-app \
          --resource-group projectbank \
          --src functions.zip

    # -------------------------------
    # 3. DEPLOY DATABRICKS NOTEBOOKS
    # -------------------------------
    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        cat <<EOF > ~/.databricks/config
        [DEFAULT]
        host = ${{ secrets.DATABRICKS_HOST }}
        token = ${{ secrets.DATABRICKS_TOKEN }}
        EOF

    - name: Upload Notebooks
      run: |
        for f in databricks/notebooks/*.py; do
          databricks workspace import --overwrite "$f" "/Repos/${{ github.actor }}/$(basename $f)"
        done

    # -------------------------------
    # 4. (OPTIONAL) RUN A JOB AFTER DEPLOY
    # -------------------------------
    - name: Trigger Databricks Job
      run: |
        echo "Job triggered (optional)"
